### ISSUE TITLE
Our systems have detected unusual activity from your system. Please try again later.

### ISSUE THREAD

**Issue by pimvanberlo** [hydrotho/ChatGPT_Model_Switcher#1]
I get this error when switching from gpt3 to gpt4 mid conversation
Browser: Opera
No other plugins installed

app-e4816c996c959118.js:14 UserError: Our systems have detected unusual activity from your system. Please try again later.
    at _app-e4816c996c959118.js:42:212751
    at main-35ce5aa6f4f7a906.js:1:106888
    at Object.next (main-35ce5aa6f4f7a906.js:1:106993)
    at n (main-35ce5aa6f4f7a906.js:1:107742)
    at u (main-35ce5aa6f4f7a906.js:1:107939)
(

It seems that the maker of the plugin: "SuperPowerChatgpt" was able to fix it in this commit. Using their extension I am able to switch between gpt3.5 and gpt4 mid conversation. It would be really great if this was possible with this script.
https://github.com/saeedezzati/superpower-chatgpt/commit/d3e60ad07dc24b4c5380420e0f4562691392f02e

https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/43149220/41a78ce3-1297-40ab-86f5-96d9b45134ad

**Comment by hydrotho** [comment]
Thank you for opening this issue. It appears that an `arkose_token` field has been added to each ChatGPT conversation request, and currently only GPT-4 models are validating this field.

When a conversation is initiated from the GPT-3.5 page, the `arkose_token` is `null`. However, when a conversation is initiated from the GPT-4 page, an automatic request is made to fetch this `arkose_token`, which is then included in the conversation request.

It seems this is part of the Arkose FunCAPTCHA challenge process. However, the GPT-4 Mobile model isn't checking for this field at this time. As a workaround, you might want to use the GPT-4 Mobile model, which does not have usage restrictions at present.

I'll aim to address this issue as soon as I get some free time. Thanks for your patience and understanding.

**Comment by hydrotho** [comment]
@pimvanberlo

Just wanted to let you know that I've addressed the issue you've reported.

But keep in mind, as ChatGPT is increasing its checks, we might see similar issues in the future. If you run into any more problems, please open a new issue.

Thanks for helping to improve this project!

If you find this project helpful, a star to support it would be greatly appreciated!

**Comment by pimvanberlo** [comment]
Thank you for fixing the issue

**Comment by gchust** [comment]
@pimvanberlo 
Is the fix working for you?  I am still facing the same error.
![image](https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/5254737/fa711768-8e72-4508-8b40-1c58996f9366)

**Comment by hydrotho** [comment]
@gchust

Please try using v1.1.0 as this issue should have been temporarily resolved.
