### ISSUE TITLE
聊天内容自动消失

### ISSUE THREAD

**Issue by stdio159** [hydrotho/ChatGPT_Model_Switcher#15]
从前天开始这种情况发生概率逐渐增加 到现在可能话说到一半 然后所有聊天记录全部没有 不是清空了账号的所有聊天记录 而是当前的聊天记录没有了 我当时把 Chat history & training 功能关闭了 
被清空的时间不固定 很随机 但是概率极其高 请问怎么办

**Comment by leichinkang** [comment]
如何将脚本转换为镜像站也可以使用，我试着把里边的chat.openai.com换成自己的pandoranext镜像站，发现不行……
