### ISSUE TITLE
手机版在今年6月就已经没有次数限制解除了。

### ISSUE THREAD

**Issue by wodaimnd** [hydrotho/ChatGPT_Model_Switcher#17]
手机版在今年6月就已经没有次数限制解除了。

**Comment by hydrotho** [comment]
[README_zh (v1.2.1)](https://github.com/hydrotho/ChatGPT_Model_Switcher/blob/v1.2.1/README_zh.md)

![image](https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/42911474/7a2e8972-ae8c-49fd-93f2-b35db0fa4d06)

[README_zh (v2.0.0)](https://github.com/hydrotho/ChatGPT_Model_Switcher/blob/v2.0.0/README_zh.md)

![image](https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/42911474/e1432326-1de3-4ddd-b2c3-13a6ab3c614b)

**Comment by hydrotho** [comment]
OpenAI 在6月底就加上限制了，所以后面我也不怎么维护该项目了。

**Comment by hydrotho** [comment]
下次更新时，我将彻底移除与此相关的描述。
