### ISSUE TITLE
On/off switch gone

### ISSUE THREAD

**Issue by pimvanberlo** [hydrotho/ChatGPT_Model_Switcher#18]
![image](https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/43149220/aa79d20c-be31-49cb-ac95-3ec1adc5fc09)

**Comment by pimvanberlo** [comment]
Using version 2.0.1

**Comment by hydrotho** [comment]
@pimvanberlo Fixed. Please update to the latest version to see the changes.
