### ISSUE TITLE
必须结合油猴使用吗，能否通过js注入

### ISSUE THREAD

**Issue by johnsonwong666** [hydrotho/ChatGPT_Model_Switcher#24]

**Comment by hydrotho** [comment]
本项目实现的是一个用户脚本（Userscript），你需要一个用户脚本管理器（Userscript Manager）来安装使用它。

参考资料：

1. [Userscript - Wikipedia](https://en.wikipedia.org/wiki/Userscript)
2. [Userscript Manager - Wikipedia](https://en.wikipedia.org/wiki/Userscript_manager)
