### ISSUE TITLE
Add security checksumming so that security setting "Subresource Integrity" can be set to "Enforce"

### ISSUE THREAD

**Issue by dreirund** [hydrotho/ChatGPT_Model_Switcher#26]
You download an external resource, https://cdn.jsdelivr.net/npm/vue@3.3.13/dist/vue.global.prod.js.

Can you add security checksumming, so that while in Tampermonkey the security setting "Subresource Integrity" is set to "Enforce" the script still works?

Regards!

**Comment by hydrotho** [comment]
Please update to [v2.0.3](https://github.com/hydrotho/ChatGPT_Model_Switcher/raw/v2.0.3/dist/chatgpt-model-switcher.user.js) and it should work.

**Comment by dreirund** [comment]
> Please update to
> [v2.0.3](https://github.com/hydrotho/ChatGPT_Model_Switcher/raw/v2.0.3/dist/chatgpt-model-switcher.user.js)
> and it should work.

Yes, thanks
