### ISSUE TITLE
不能兼容潘多拉next的应用

### ISSUE THREAD

**Issue by yuzhegan** [hydrotho/ChatGPT_Model_Switcher#28]
![1709363371461.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1709363371461.png)

**Comment by yuzhegan** [comment]
下拉框不显示内容

**Comment by hydrotho** [comment]
本人没有用过 Pandora Next 项目，请给个测试环境，我有空看看 API 兼容性，试试能不能适配。

**Comment by yuzhegan** [comment]
chat.topgpts.us直接用账号登陆就行啦

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月02日 15:50 |
| 收件人 | hydrotho/ChatGPT_Model_Switcher ***@***.***> |
| 抄送人 | yuzhegan ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [hydrotho/ChatGPT_Model_Switcher] 不能兼容潘多拉next的应用 (Issue #28) |

本人没有用过 Pandora Next 项目，请给个测试环境，我有空看看 API 兼容性，试试能不能适配。

**Comment by yuzhegan** [comment]
油猴脚本能更新下吗

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月02日 22:00 |
| 收件人 | hydrotho/ChatGPT_Model_Switcher ***@***.***> |
| 抄送人 | yuzhegan ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [hydrotho/ChatGPT_Model_Switcher] 不能兼容潘多拉next的应用 (Issue #28) |

Closed #28 as completed via #29.

**Comment by hydrotho** [comment]
已更新 [v2.2.0](https://github.com/hydrotho/ChatGPT_Model_Switcher/blob/v2.2.0/dist/chatgpt-model-switcher.user.js)

**Comment by yuzhegan** [comment]
谢谢，辛苦啦

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月03日 00:38 |
| 收件人 | hydrotho/ChatGPT_Model_Switcher ***@***.***> |
| 抄送人 | yuzhegan ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [hydrotho/ChatGPT_Model_Switcher] 不能兼容潘多拉next的应用 (Issue #28) |

已更新 v2.2.0
