### ISSUE TITLE
Hello，最近的ChatGPT好像是失效了

### ISSUE THREAD

**Issue by gaozishun** [hydrotho/ChatGPT_Model_Switcher#30]
Hello，最近的ChatGPT好像是失效了，请问作者未来还更新吗？非常好用

**Comment by hydrotho** [comment]
请提供复现失效情况的具体流程。

我自己测试是可以正常调用 `gpt-4-mobile` 模型的。

**Comment by gaozishun** [comment]
> 请提供复现失效情况的具体流程。
> 
> 我自己测试是可以正常调用 `gpt-4-mobile` 模型的。

你好，作者，我在使用ChatGPT4.0的时候，昨天好像还没有突破使用限制，但是今天就开始限额了（就是说突破限制失效了）

**Comment by gaozishun** [comment]
您所说的gpt-4-mobile确实是可以使用，但是好像对于多余3小时40条的的使用数量的权限失效了（难道是我使用的过于频繁所致？）

**Comment by leonzhang2** [comment]
是的，模型可以切换，但是开始按照You've reached the current usage cap for GPT-4. 40条限制了，之前模型是可以突破次数限制的。大概是前天中午11点左右调整的。

**Comment by huihuibest** [comment]
是的，现在确实会有上限的问题，无法突破次数限制了
