### ISSUE TITLE
GPT-4 Mobile consumed all my credits

### ISSUE THREAD

**Issue by victoremanuelgo** [hydrotho/ChatGPT_Model_Switcher#6]
After installing the script and using GPT-4 Mobile for some time I received the error message: You've reached the current usage cap for GPT-4. You can continue with the default model now, or try again after 1:33 AM. [Learn more]

**Comment by victoremanuelgo** [comment]
Is there any alternative to use GPT-4 without usage limitations?

**Comment by hydrotho** [comment]
> Is there any alternative to use GPT-4 without usage limitations?

I don't know any alternatives at the moment.

**Comment by hydrotho** [comment]
> > ChatGPT has implemented a usage cap for the GPT-4 Mobile model. If you're using the web version, you may encounter: "You've reached the current usage cap for GPT-4. You can continue with the default model now, or try again after XXX." If you're using the iOS version, you may encounter: "You have sent too many messages to the model. Please try again later."
> 
> What is the cap limit? Is the cap separate from the main model?

The GPT-4 model's usage cap, which is currently set to 25 messages every 3 hours, applies to both the web version and the iOS app. This means the cap is not specific to each platform, but rather is a shared limit. If you reach this cap, you will need to wait until the 3-hour period resets before you can continue using the GPT-4 model.

**Comment by hydrotho** [comment]
GPT-4 currently has a cap of 50 messages every 3 hours.
