### ISSUE TITLE
The option of GPT-4 mobile has been disabled

### ISSUE THREAD

**Issue by yang-wang11** [hydrotho/ChatGPT_Model_Switcher#9]
Is the policy or rule of openAI changed? the toggle of GPT-4 mobile is grey
<img width="212" alt="image" src="https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/94777185/88dfdcf7-fb1a-4f16-92d9-49a8f3b52a7a">

**Comment by hydrotho** [comment]
The mobile series models, GPT-3.5 (Mobile) and GPT-4 (Mobile), are now available. However, the usage of the GPT-4 Web Browsing model is still temporarily disabled by OpenAI. We have to wait for OpenAI's decision to reactivate it.
